name: Create GitHub Release from pyproject.toml version

on:
  push:
    branches:
      - main
#   pull_request:
#     types: [closed]
#     branches:
#       - main
#     if: github.event.pull_request.merged == true

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Get package version
        id: package_version
        run: |
          VERSION=$(uvx --from=toml-cli toml get --toml-path=pyproject.toml project.version)
          echo "PACKAGE_VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Fetch all tags
        run: git fetch --tags
      - name: Check if tag already exists
        id: check_tag
        run: |
          TAG=$(git tag --list "$PACKAGE_VERSION")
          echo "TAG_VERSION=$TAG" >> "$GITHUB_ENV"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: ${{ env.PACKAGE_VERSION != env.TAG_VERSION }}
        with:
          tag_name: ${{ env.PACKAGE_VERSION }}
          name: Release v${{ env.PACKAGE_VERSION }}
          body: |
            Automated release created from push to main branch.
            See `pyproject.toml` for version details.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

